export enum FoodProp {
  name = 'name',
  source = 'source',
  notes = 'notes',
  calories = 'calories',
  proteins = 'proteins',
  carbs = 'carbs',
  fats = 'fats',
  fibres = 'fibres',
  sugar = 'sugar',
  starch = 'starch',
  saturated = 'saturated',
  trans = 'trans',
  cholesterol = 'cholesterol',
  sodium = 'sodium',
  calcium = 'calcium',
  potassium = 'potassium',
  magnesium = 'magnesium',
  omega3 = 'omega3',
  omega6 = 'omega6',
  zinc = 'zinc',
  iron = 'iron',
  alcohol = 'alcohol',
  fatPercentage = 'fatsPercentage',
  carbsPercentage = 'carbsPercentage',
  proteinsPercentage = 'proteinsPercentage',
  detailsPercentage = 'detailsPercentage'
}
