import { NgModule } from '@angular/core';
import {
  MatTabsModule,
  MatCardModule,
  MatFormFieldModule,
  MatIconModule,
  MatInputModule,
  MatButtonModule,
  MatDividerModule,
  MatSidenavModule,
  MatSelectModule,
  MatRippleModule,
  MatMenuModule,
  MatBadgeModule,
  MatListModule,
  MatSnackBarModule,
  MatToolbarModule,
  MatTableModule,
  MatButtonToggleModule,
  MatPaginatorModule,
  MatExpansionModule,
  MatDialogModule,
  MatGridListModule,
  MatChipsModule
} from '@angular/material';
import { ReactiveFormsModule } from '@angular/forms';

@NgModule({
  declarations: [],
  imports: [
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatTabsModule,
    MatCardModule,
    MatButtonModule,
    ReactiveFormsModule,
    MatDividerModule,
    MatSidenavModule,
    MatSelectModule,
    MatRippleModule,
    MatDividerModule,
    MatMenuModule,
    MatBadgeModule,
    MatListModule,
    MatSnackBarModule,
    MatToolbarModule,
    MatTableModule,
    MatPaginatorModule,
    MatButtonToggleModule,
    MatExpansionModule,
    MatDialogModule,
    MatGridListModule,
    MatChipsModule
  ],
  exports: [
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatTabsModule,
    MatCardModule,
    MatButtonModule,
    ReactiveFormsModule,
    MatDividerModule,
    MatSidenavModule,
    MatSelectModule,
    MatRippleModule,
    MatDividerModule,
    MatMenuModule,
    MatBadgeModule,
    MatListModule,
    MatSnackBarModule,
    MatToolbarModule,
    MatTableModule,
    MatPaginatorModule,
    MatButtonToggleModule,
    MatExpansionModule,
    MatDialogModule,
    MatGridListModule,
    MatChipsModule
  ]
})
export class MaterialModule {}
